import { v4 as uuidv4 } from 'uuid';
import { ProductEntity } from '../domains/Product.entity';

function formatDate(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');

  return `${year}-${month}-${day} `;
}

export const dataMock: ProductEntity[] = [
  {
    id: uuidv4(),
    name: 'Сервер 1',
    type: 'Сервер',
    location: 'Кабинет 101',
    organizationUnit: 'Отдел IT',
    inventoryNumber: '1',
    tags: ['Mac'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 1',
    type: 'Компьютер',
    location: 'Кабинет 102',
    organizationUnit: 'Отдел продаж',
    inventoryNumber: '2',
    tags: ['Windows', 'Linux', 'Mac'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 2',
    type: 'Сервер',
    location: 'Кабинет 103',
    organizationUnit: 'Бухгалтерия',
    inventoryNumber: '3',
    tags: ['Mac'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 2',
    type: 'Компьютер',
    location: 'Кабинет 104',
    organizationUnit: 'Снабжение',
    inventoryNumber: '4',
    tags: ['Windows', 'Linux'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 3',
    type: 'Сервер',
    location: 'Кабинет 105',
    organizationUnit: 'Директор',
    inventoryNumber: '5',
    tags: ['Mac', 'Linux'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 3',
    type: 'Компьютер',
    location: 'Кабинет 106',
    organizationUnit: 'Отдел IT',
    inventoryNumber: '6',
    tags: ['Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 4',
    type: 'Сервер',
    location: 'Кабинет 107',
    organizationUnit: 'Бухгалтерия',
    inventoryNumber: '7',
    tags: ['Mac', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 4',
    type: 'Компьютер',
    location: 'Кабинет 108',
    organizationUnit: 'Снабжение',
    inventoryNumber: '8',
    tags: ['Linux'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 5',
    type: 'Сервер',
    location: 'Кабинет 109',
    organizationUnit: 'Директор',
    inventoryNumber: '9',
    tags: ['Mac', 'Linux', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 5',
    type: 'Компьютер',
    location: 'Кабинет 110',
    organizationUnit: 'Отдел IT',
    inventoryNumber: '10',
    tags: ['Linux'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 6',
    type: 'Сервер',
    location: 'Кабинет 111',
    organizationUnit: 'Бухгалтерия',
    inventoryNumber: '11',
    tags: ['Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 6',
    type: 'Компьютер',
    location: 'Кабинет 112',
    organizationUnit: 'Снабжение',
    inventoryNumber: '12',
    tags: ['Mac', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 7',
    type: 'Сервер',
    location: 'Кабинет 113',
    organizationUnit: 'Директор',
    inventoryNumber: '13',
    tags: ['Linux'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 7',
    type: 'Компьютер',
    location: 'Кабинет 114',
    organizationUnit: 'Отдел IT',
    inventoryNumber: '14',
    tags: ['Mac', 'Linux', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 8',
    type: 'Сервер',
    location: 'Кабинет 115',
    organizationUnit: 'Бухгалтерия',
    inventoryNumber: '15',
    tags: ['Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 8',
    type: 'Компьютер',
    location: 'Кабинет 116',
    organizationUnit: 'Снабжение',
    inventoryNumber: '16',
    tags: ['Mac', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 9',
    type: 'Сервер',
    location: 'Кабинет 117',
    organizationUnit: 'Директор',
    inventoryNumber: '17',
    tags: ['Linux'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 9',
    type: 'Компьютер',
    location: 'Кабинет 118',
    organizationUnit: 'Отдел IT',
    inventoryNumber: '18',
    tags: ['Mac', 'Linux', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Сервер 10',
    type: 'Сервер',
    location: 'Кабинет 119',
    organizationUnit: 'Бухгалтерия',
    inventoryNumber: '19',
    tags: ['Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
  {
    id: uuidv4(),
    name: 'Компьютер 10',
    type: 'Компьютер',
    location: 'Кабинет 120',
    organizationUnit: 'Снабжение',
    inventoryNumber: '20',
    tags: ['Mac', 'Windows'],
    createdAt: formatDate(new Date()),
    updatedAt: formatDate(new Date()),
    auditDate: formatDate(new Date()),
  },
];
